// Standalone migration runner. Used by `pnpm db:migrate` and CI.
// Reads DATABASE_URL from env (the repo-root .env loaded by tsx).
//
// Migrations live in src/db/migrations and are generated by
// `pnpm db:generate` from the schema in src/db/schema/.

import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { Client } from 'pg';
import { config } from 'dotenv';
import { resolve } from 'node:path';

// Load repo-root .env — services/api lives two levels deep.
config({ path: resolve(__dirname, '../../../../.env') });

async function runMigrations(): Promise<void> {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    throw new Error('DATABASE_URL is required');
  }

  const client = new Client({ connectionString: databaseUrl });
  await client.connect();

  const db = drizzle(client);
  // eslint-disable-next-line no-console
  console.log('running migrations...');
  await migrate(db, { migrationsFolder: resolve(__dirname, 'migrations') });
  // eslint-disable-next-line no-console
  console.log('migrations complete');

  await client.end();
}

runMigrations().catch((err) => {
  // eslint-disable-next-line no-console
  console.error('migration failed', err);
  process.exit(1);
});
